#!/usr/bin/python
# -*- coding: UTF-8 -*-

try:
    fh = open("testfile", "w")
    fh.write("这是一个测试文件，用于测试异常!!")
except IOError:
    print "Error: 没有找到文件或读取文件失败"
else:
    print "内容写入文件成功"
    fh.close()
                      
   内容写入文件成功
   
 ========================= RESTART: D:/tsl/11.17-2.py =========================  
   
   
    try:
    fh = open("testfile", "w")
    try:
        fh.write("这是一个测试文件，用于测试异常!!")
        
    finally:
        print "关闭文件"
        fh.close()
except IOError:
    print "Error: 没有找到文件或读取文件失败"
 
     关闭文件
========================= RESTART: D:/tsl/11.17-2.py =========================         
     
     
     # -*- coding: cp936 -*-
def temp_convert(var):
    try:
        return int(var)
    except ValueError, Argument:
        print "参数没有包含数字\n", Argument

temp_convert("xyz");

参数没有包含数字
invalid literal for int() with base 10: 'xyz'
